### ISSUE TITLE
Device list doesn't return Washer

### ISSUE THREAD

**Issue by alexanv1** [sampsyo/wideq#46]
I have 3 SmartThinQ devices (Dishwasher, Washer and Dryer).
Dishwasher and Dryer are returned in the device list but Washier is, for whatever reason, is missing.

I've debugged it as far as I could and it looks like the data returned from POST to device\deviceList just doesn't contain the Washer for some reason. The washer is on the same account and works fine in SmartThinQ app.

I've seen recent mention on HA forum of LG changing their API endpoints.
So, perhaps, there is another API endpoint that could possibly be used instead of device\deviceList to get the list of devices?

**Comment by geekofweek** [comment]
I've got a similar issue, it will poll the Refrigerator, Dishwasher, and Stove but not the new Washer and Dryer.

**Comment by rangerek** [comment]
same here :) no errors and just no washer reporting

**Comment by geekofweek** [comment]
I've been trying to put some effort behind this when I can.  It looks like my smart thinQ app calls up aic.lgthinq.com and not kic.kgthinq.com.  I also hit both the us.lgeapi.com and kr.lgeapi.com.  I haven't got very far outside trying to work backwards how all of the various forked components work since It seems everyone forked and made it work for their various setups. So far I put a lot of time into doing some research.

Question for those that don't get the washer or dryer to show, when did you add it to smart thinQ?  Curious if there is a correlation between a new set of servers and APIs for newly added components.

**Comment by petewill** [comment]
@geekofweek I also do not see my washer (it is the only LG device I have so I'm not sure about the other devices).  I added it on 10/12/19 through the Android SmartThinQ app.

**Comment by reylas** [comment]
I cannot see either my washer or dryer.   No errors, just blank.   First registered on the 16th of October.

**Comment by rwarner** [comment]
Same here, just blank no errors first registered last week 10/27/19. Only an LG washer on my account

**Comment by martinc** [comment]
It seems all newly registered devices are using a new private API to communicate with LG. I've been trying to get my new heat pumps hooked up, none of them are listed by this library. I've been using charles proxy to examine the API requests that are happening in the mobile app. From initial testing, the calls are fairly complex and require alot of header values for the server to accept them. I wish LG would provide a public API, or at the very least allow scheduled temperature changes in their own app. The new hosts I'm seeing are `aic-service.lgthinq.com` and `aic.lgthinq.com`.

**Comment by sampsyo** [comment]
That's too bad! Indeed, we can all lament the lack of a public API. I spent a ridiculously large amount of time with mitmproxy, disassemblers, and staring at obfuscated JavaScript source to figure out the old API. Seems like the same process might be necessary again for the new API.

**Comment by rwarner** [comment]
Man this really is unfortunate, I was looking forward to tying this into HASS and getting some feedback on Alexa when the washer finishes. Wanted to help out with this effort but I'm not sure if I would be able to assist with any disassembly.

**Comment by tinkerborg** [comment]
I've got a good chunk of the new API figured out. The holiday here in the US will interrupt progress, but I'll try to get this finished this weekend and get a PR in.

**Comment by tinkerborg** [comment]
I haven't forgotten about this, but I probably got a bit overconfident after my initial progress, and it's taking a bit longer than I figured. 😁 While the old oauth tokens work, there is now a `x-user-no` header required. This is included in the redirect URL for the new oauth flow, which I've now got implemented. As an upshot, this also makes third-party logins work fine, though I only tested with Google.

If anyone would like to help this effort, especially if you have a mix of devices using the old and new API, let me know and I can push my fork and make you a collaborator.

**Comment by rwarner** [comment]
hey @tinkerborg I'm not sure how much time I might have. But I currently have an LG email only login (no third party flow) with only the US based Washer (on the new API change). I would definitely give it a look through, but not sure how much debugging I can do at the current moment.

Let me know how I can contribute or test anything

**Comment by kenmaples** [comment]
I seem to be in the same boat with the new API. Account was created this week with a washer and dryer added to the account. Looking forward to trying your latest updates.

**Comment by martinc** [comment]
Hey @tinkerborg I’d like to take a look at your fork. May be able to help with the effort. Only have new devices.

**Comment by tayanov** [comment]
+1

**Comment by gladhorn** [comment]
I just tried to get a capture of the network traffic of the latest Android Thinq app, but actually failed with mitm :( It seems like LG started to use certificate pinning.

**Comment by tinkerborg** [comment]
I did get a capture w/ a mitm proxy and was able to get the auth flow working, and a device list. Where I left off was working on monitor functionality. Sorry I've been unresponsive, things have been a bit hectic with work. I'll pick this back up tonight and get my fork up so folks can help get the rest working.

**Comment by sampsyo** [comment]
FWIW, when I did the original reverse engineering, I had to disable certificate pinning. This, unfortunately, required disabling two integrity checks that the app did to try to prevent tampering (one implemented in Java, which was easy, and another implemented in C/native code, which required manually editing instructions).

**Comment by tinkerborg** [comment]
OK, finally got my code pushed. Note it's very rough, I was in the middle of trying to get both API versions to coexist when I last worked on this. You should be able to go through the whole auth flow against the new API endpoints, and facebook,google and amazon auth should work fine now too.

Once authenticated you should be able to pull a device list but monitor functionality is not working yet.

@martinc and @gladhorn I added you as collaborators, if anyone else wants access let me know. `api2` branch on my fork here: https://github.com/tinkerborg/wideq/tree/api2

**Comment by rwarner** [comment]
Fantastic, I'll try to give this ago today or tomorrow and pull down your fork in my setup. Will get back to you here if I'm seeing my Washer.

Thank you for your efforts thus far @tinkerborg

**Comment by tinkerborg** [comment]
> Fantastic, I'll try to give this ago today or tomorrow and pull down your fork in my setup. Will get back to you here if I'm seeing my Washer.

Cool, I added you as a collaborator on my fork too. In theory it should see your washer, it sees my W/D w/ the new API.

**Comment by tayanov** [comment]
im test example.py -c RU -l ru-RU at russian. Logging at site, copy url back and 
Have a error
AttributeError: module 'wideq' has no attribute 'NotLoggedInError'

**Comment by tinkerborg** [comment]
> im test example.py -c RU -l ru-RU at russian. Logging at site, copy url back and
> Have a error
> AttributeError: module 'wideq' has no attribute 'NotLoggedInError'

Should be fixed.

**Comment by tayanov** [comment]
> > im test example.py -c RU -l ru-RU at russian. Logging at site, copy url back and
> > Have a error
> > AttributeError: module 'wideq' has no attribute 'NotLoggedInError'
> 
> Should be fixed.

Hi. Now i see cyrcle message.
Session expired.
Session expired.
Session expired.

And no show device. But to account attach refrige and washer.

**Comment by gladhorn** [comment]
@tayanov  https://github.com/tinkerborg/wideq/pull/1 should fix your issue. After that I still cannot see any devices, but at least the authentication works for me.

**Comment by tinkerborg** [comment]
> @tayanov [tinkerborg#1](https://github.com/tinkerborg/wideq/pull/1) should fix your issue. After that I still cannot see any devices, but at least the authentication works for me.

Latest [commit](https://github.com/tinkerborg/wideq/commit/64ab8be51ddfd5316b3ace6cc3ab6252ac1496de) should fix that, I think. Forgot to have it use the API URL returned by the gateway.

**Comment by rwarner** [comment]
Ok so I was able to sit down and try this new fork out. Unfortunately I get a blank response for listing of devices still.

Authentication flow worked totally fine though. No weird errors or anything just no washer pops up for me.

**Comment by rwarner** [comment]
Nevermind! I got it working. First time I ran it with the following:

`python3 example.py -c US -l en-US -ls`

Which looked like it caused some problems in the URL paths. Ran it again with the standard:

`python3 example.py -c US -l en-US`

Now I get the Washer!

`Washer (WASHER <model>_US_WIFI)`

**Comment by tayanov** [comment]
Now iam too take Washer. Whats component to use with home assistant?

**Comment by gladhorn** [comment]
@rwarner The command is "ls", not "-ls" (drop the minus).
@tayanov currently it's not there yet, it can only list devices with the new API, but nothing more. That's not useful in home assistant.

I also see my washer and dryer now finally \o/ progress.

**Comment by tayanov** [comment]
> @rwarner Команда "ls", а не "-ls" (минус).
> @tayanov в данный момент его еще нет, он может перечислять только устройства с новым API, но не более того. Это не полезно в домашнем помощнике.
> 
> Я также вижу мою стиральную машину и сушилку теперь наконец \ O / прогресс.

may be @sampsyo can add this apiv2 to self repo?

**Comment by rwarner** [comment]
@gladhorn good point. Just so used `ls -la`... for example.

I tried to run monitor and get things working but wasn't successful last night. Wasn't able to get an appropriate response after trying to implement the `lgedm_post()` method. Was erroring out. I assume like tinkerborg said earlier the monitor has to be finished, but didn't know where to start besides post and bringing in the right headers. I might not have enough information myself from sniffing the traffic / apis like you guys might have.

**Comment by tinkerborg** [comment]
@tayanov Yes, the goal is a pull request but it's premature for that right now.

@rwarner It uses a totally different endpoint and header format, so the old `lgedm_post()` won't be useful for the new API. I'll try to pick this up again tonight/this weekend and see if I can get monitor working.

**Comment by rwarner** [comment]
@tinkerborg yeah I had a feeling that was probably the case. Thanks for verifying, glad I just went to bed.

Do you mind if I ask how I might go about reproducing the methods you're using for figuring out the endpoints / headers? Or is that better off letting you wrap it up if you have it all on your end.

**Comment by gladhorn** [comment]
I'll prepare some merge requests to slowly add the new API in parallel with the existing code.
Note that this is not production ready, there is no way to use it in home assistant yet.

**Comment by gladhorn** [comment]
@tinkerborg in case you continue working on this, I took your code and merged it into the original code (I gave up trying to maintain both in parallel). Feel free to continue on top of https://github.com/gladhorn/wideq/tree/api2_merged

**Comment by tinkerborg** [comment]
> @tinkerborg in case you continue working on this, I took your code and merged it into the original code (I gave up trying to maintain both in parallel). Feel free to continue on top of https://github.com/gladhorn/wideq/tree/api2_merged

I had kept them separate intentionally, with the goal of supporting both APIs. The idea was to ultimately move any common logic into a base class from which both cores inherit, and submit a PR back to the original repo.

**Comment by gladhorn** [comment]
> > @tinkerborg in case you continue working on this, I took your code and merged it into the original code (I gave up trying to maintain both in parallel). Feel free to continue on top of https://github.com/gladhorn/wideq/tree/api2_merged
> 
> I had kept them separate intentionally, with the goal of supporting both APIs. The idea was to ultimately move any common logic into a base class from which both cores inherit, and submit a PR back to the original repo.

Sure, I just wonder, if there's any point in keeping both APIs working - I think LG has moved on, so we should rather focus on getting one of the APIs working sensibly. The new API should work for all devices as far as I can tell, so I'd just go for that. Anyway, we'll have to get it to work first, then it can always be refactored to either support both or just one. Thanks for your work! Feel free to just continue with your branch :) I just had to play with it, since I usually understand code a lot better by somehow changing it, so it's generally a good learning experience to try moving stuff around.

**Comment by Woodpeckercz** [comment]
This one finally worked for me :+1: 
https://github.com/gladhorn/wideq/tree/api2_merged

**Comment by tayanov** [comment]
> Этот наконец-то сработал для меня 
> https://github.com/gladhorn/wideq/tree/api2_merged

with ha?

**Comment by Woodpeckercz** [comment]
> 
> 
> > Этот наконец-то сработал для меня
> > https://github.com/gladhorn/wideq/tree/api2_merged
> 
> with ha?

i'm running Hassio and I'm currently trying to implement it in, so can't confirm just yet.

**Comment by rwarner** [comment]
None of the current code with APIv2 supports monitoring so it wouldn't be able to be "implemented into HA" until the code supports such a thing. AFAIK

Unless "api2_merged" branch has resolved this

**Comment by martinc** [comment]
Ok I finally got a chance to work on it today. I was able to get POST working, and have tested monitoring and commanding my heat pumps, and it's working!

@tinkerborg here's my PR: https://github.com/tinkerborg/wideq/pull/4/files

**Comment by jmh600cbr** [comment]
> Ok I finally got a chance to work on it today. I was able to get POST working, and have tested monitoring and commanding my heat pumps, and it's working!
> 
> @tinkerborg here's my PR: https://github.com/tinkerborg/wideq/pull/4/files

hey thanks for your hard work. I'm a total noob and have been trying to use the [home bridge version ](https://github.com/NorDroN/homebridge-wideq)of this but it seems to have stopped working. Any chance you can help me fix this one?

**Comment by sampsyo** [comment]
FYI, @jmh600cbr, the bottom line is that I don't think the work is ready yet for you to use. People are still working on making it work in Python. The Homebridge plugin relies on a JavaScript port, so that will likely take longer.

**Comment by jmh600cbr** [comment]
> FYI, @jmh600cbr, the bottom line is that I don't think the work is ready yet for you to use. People are still working on making it work in Python. The Homebridge plugin relies on a JavaScript port, so that will likely take longer.

Thanks! Hoping for results soon!

**Comment by tinkerborg** [comment]
@jmh600cbr Thanks for the effort, but that is still hitting the old device URL, so it won't work with devices like my washer/dryer.

That said, I've made a big breakthrough tonight and have the pieces needed to implement monitor functionality. I need to call it a night for now, and I have a lot of cleanup to do before sharing, but stay tuned...

```- {"data":{"state":{"reported":{"meta":{"allDeviceInfoUpdate":false,"messageId":"zREohzjLT0uZ87kgbt7tLw"},"mid":21482972,"online":true,"static":{"countryCode":"US","deviceType":"202"},"timestamp":1580098081135,"washerDryer":{"initialTimeMinute":6}}}},"deviceId":"REDACTED","type":"monitoring"}
- {"data":{"state":{"reported":{"meta":{"allDeviceInfoUpdate":false,"messageId":"EL6_xyZ7SZCnVhyEmN7g5Q"},"mid":21503770,"online":true,"static":{"countryCode":"US","deviceType":"202"},"timestamp":1580098101583,"washerDryer":{"preState":"COOLING","remoteStart":"REMOTE_START_OFF","state":"END"}}}},"deviceId":"REDACTED","type":"monitoring"}
- {"data":{"state":{"reported":{"meta":{"allDeviceInfoUpdate":false,"messageId":"wPDbmf-tS52hvGkGnJmzkA"},"mid":21534086,"online":true,"static":{"countryCode":"US","deviceType":"202"},"timestamp":1580098131209,"washerDryer":{"courseDryer27inchBase":"NOT_SELECTED","downloadedCourseDryer27inchBase":"NOT_SELECTED","dryLevel":"NO_DRYLEVEL","energySaver":"ENERGYSAVER_OFF","initialTimeMinute":1,"preState":"END","state":"POWEROFF","temp":"NO_TEMP"}}}},"deviceId":"REDACTED","type":"monitoring"}
- {"data":{"state":{"reported":{"meta":{"allDeviceInfoUpdate":false,"messageId":"-0lfAebaRhiygvoVbAkSeQ"},"mid":21535109,"online":true,"static":{"countryCode":"US","deviceType":"202"},"timestamp":1580098132192,"washerDryer":{"downloadedCourseDryer27inchBase":"SUPERDRY"}}}},"deviceId":"REDACTED","type":"monitoring"}
```

**Comment by NorDroN** [comment]
@jmh600cbr
As @sampsyo said, [homebridge-wideq](https://github.com/NorDroN/homebridge-wideq) is focused on using the port of this library for nodejs and of course I'm watching this repository.
When this library switches to the new version of LG API, I will also try to transfer these changes to the nodejs port

**Comment by tinkerborg** [comment]
More progress, wish I had more time to work on this. So, the new API is using MQTT. Specifically, it's using AWS IoT MQTT service, with client certificate auth. There is an LG API endpoint that will accept a CSR in a POST and return a certificate used for client auth, along with an MQTT topic. There's another endpoint with which you can retrieve the MQTT endpoint host/port.

Still not ready to send a PR back to this project, but my fork can now manage all of the above and ultimately subscribe to an MQTT topic in response to a `monitor_start` call. It's a fairly short path from there to actual device monitor functionality. Once that's done there will be a fair amount of refactoring to be done so both API versions can coexist, along with adding some unit tests. Once that's all done I should be ready to open a PR for API for initial API v2 support. 

Again if anyone wants to help I can give you contributor access to the fork directly.

**Comment by bakazm** [comment]
I recently got an lg washer and dryer. We already had an lg dishwasher. All 3 are connected to the lg app, but only the dish washer and washer are reported by wideq. could it be related to the different API's? I'd be happy to help test.

**Comment by honestbleeps** [comment]
thanks so much for the hard work on this -- curious if there's any active work continuing, and/or guidance on how we could help?

I just got it up and running, got authenticated, got it to see my washer and dryer, but then it errors with an API exception...

first, the washer/dryer output (with uuids edited for safety):

```
some-uuid-here-that-seems-valid: Dryer (DRYER RV13U7JS9W_D_US_WIFI)
some-uuid-here-that-seems-valid: Washer (WASHER T1872EFHU_F)
````

the next line, though, the traceback/error starts. Here's the last bit of the traceback:

```
  File "/Users/honestbleeps/Code/wideq/wideq/core_v2.py", line 302, in post
    return thinq2_post(url, data, self.auth.access_token, self.auth.user_number, country=self.auth.gateway.country, language=self.auth.gateway.language)
  File "/Users/honestbleeps/Code/wideq/wideq/core_v2.py", line 139, in thinq2_post
    raise APIError(code, "error")
wideq.core_exceptions.APIError: ('0101', 'error')
```
any idea what code 0101 might mean?  the login seemed successful, I saw my washer/dryer, so I wonder if it's something nonfatal that just needs to be added as an acceptable condition?

**Comment by tinkerborg** [comment]
@honestbleeps I'm still working on it, yes. I've got the reverse engineering part basically figured out for the new API. I haven't had time lately to finish polishing this into a viable PR, but I expect to have time again next week. If anyone wants to help, please let me know. 

Are you just trying `example.py` when you see this error?

**Comment by honestbleeps** [comment]
@tinkerborg yeah, just `example.py` unedited, it does successfully find my washer/dryer, but then poops out.  starting on line 225 of `example.py`, but I figure the main relevant thing is the API response code of 0101 which seems unexpected/odd.

**Comment by James712346** [comment]
Yeah, `example.py` lists my devices but then tries to post to the API and gets a 0101 error:
```bash 
UUID : Refrigerator (REFRIGERATOR 2REF12EIIFW__)
Traceback (most recent call last):
  File "example.py", line 225, in <module>
    main()
  File "example.py", line 221, in main
    example(args.country, args.language, args.cmd, args.args)
  File "example.py", line 193, in example
    state = client.dump()
  File "/home/user/Documents/wideq-api2/wideq/client.py", line 191, in dump
    out['session'] = self._session.dump()
  File "/home/user/Documents/wideq-api2/wideq/core_v2.py", line 437, in dump
    'monitor': self.monitor.dump()
  File "/home/user/Documents/wideq-api2/wideq/core_v2.py", line 318, in monitor
    self._monitor = AWSMQTTMonitor.from_session(self)
  File "/home/user/Documents/wideq-api2/wideq/core_v2.py", line 563, in from_session
    auth = AWSMQTTAuth.from_session(session)
  File "/home/user/Documents/wideq-api2/wideq/core_v2.py", line 493, in from_session
    cert_data = session.post('service/users/client/certificate', {
  File "/home/user/Documents/wideq-api2/wideq/core_v2.py", line 302, in post
    return thinq2_post(url, data, self.auth.access_token, self.auth.user_number, country=self.auth.gateway.country, language=self.auth.gateway.language)
  File "/home/user/Documents/wideq-api2/wideq/core_v2.py", line 139, in thinq2_post
    raise APIError(code, "error")
wideq.core_exceptions.APIError: ('0101', 'error')
```

**Comment by canadaohcanada** [comment]
Given the success in https://github.com/ollo69/ha-smartthinq-washer/issues/3 with resolving this for washer/dryer pairs, is there any update to this problem?

**Comment by stefxx** [comment]
Great, I can find my new devices using the https://github.com/gladhorn/wideq/tree/api2_merged branch. However, controlling them fails consistently with the error below. Anyone having more success with this? Seems like the "post" function is still missing...

Traceback (most recent call last):
  File "example.py", line 238, in <module>
    main()
  File "example.py", line 234, in main
    example(args.country, args.language, args.cmd, args.args)
  File "example.py", line 194, in example
    example_command(client, cmd, args)
  File "example.py", line 170, in example_command
    func(client, *args)
  File "example.py", line 140, in turn
    ac.set_on(on_off == 'on')
  File "wideq-api2_merged\wideq\ac.py", line 234, in set_on
    self._set_control('Operation', op_value)
  File "wideq-api2_merged\wideq\client.py", line 422, in _set_control
    self.client.session.set_device_controls(
  File "wideq-api2_merged\wideq\core.py", line 443, in set_device_controls
    return self.post('rti/rtiControl', {
AttributeError: 'Session' object has no attribute 'post'

**Comment by stefxx** [comment]
Ignore my last post, I deleted it. I was working with the wrong branch.

Now, with the correct version installed, I am getting the 0101 error as posted above. Any progress on this, or did anyone find a workaround?

Thanks!

**Comment by One-P** [comment]
I installed an AC-unit and when following the instructions, the ls command does not return anything.

Are there any logs or other actions, I can take to help with this issue; my end goal is to get my AC unit to work with homebridge.

**Comment by canadaohcanada** [comment]
@One-P you're probably in the same boat as me. New devices added to the ThinQ system go under the new API rather than the old one which WideQ was designed to support. There are people who have worked out the new API, but it hasn't all been put into one place for us "end users" to enjoy.

**Comment by stefxx** [comment]
Make sure to use the api2 version here: https://github.com/tinkerborg/wideq/tree/api2/wideq

After showing devices, you probably receive an 0101 error. But at least it shows all my devices!

**Comment by stefxx** [comment]
Make sure to use the api2 version here: https://github.com/tinkerborg/wideq/tree/api2/wideq

After showing devices, you probably receive an 0101 error. But at least it shows all my devices!

**Comment by stefxx** [comment]
It seems the 0101 error is related to the VeriSign certificate. The URL is giving a 301 (Moved Permamently) error.

`GET https://www.symantec.com/content/en/us/enterprise/verisign/roots/VeriSign-Class%203-Public-Primary-Certification-Authority-G5.pem HTTP/1.1
Host: www.symantec.com
User-Agent: python-requests/2.23.0
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive


HTTP/1.1 301 Moved Permanently
Date: Wed, 22 Apr 2020 17:17:21 GMT
Content-Type: text/html; charset=iso-8859-1
Content-Length: 245
Connection: keep-alive
Server: Apache
Strict-Transport-Security: max-age=15768000
Location: https://www.broadcom.com/404-symantec

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://www.broadcom.com/404-symantec">here</a>.</p>
</body></html>


------------------------------------------------------------------
GET https://www.broadcom.com/404-symantec HTTP/1.1
Host: www.broadcom.com
User-Agent: python-requests/2.23.0
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive


HTTP/1.1 404 Not Found
Date: Wed, 22 Apr 2020 17:17:22 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Server: nginx
Last-Modified: Invalid date GMT
Content-Encoding: gzip
`

**Comment by tinkerborg** [comment]
> It seems the 0101 error is related to the VeriSign certificate. The URL is giving a 301 (Moved Permamently) error.

That's correct, but fixing that will throw another error since I was not correctly generating/registering a client ID. I've got that part sorted now too and am continuing to work on this again (finally) this week. Stay tuned...

**Comment by stefxx** [comment]
Great!

**Comment by heardv** [comment]
Thanks for taking the time for this. I have recently added my LG washer and dryer to the their app. I had previously set it up some couple years ago. How do I know which API/code I need to use? I'm running HOOBS Version 3.1.27 with the plugin:

Lg Airco
0.0.999 published 10/26/2019
Homebridge plugin to control a Smart Thinq enabled LG airco unit. Makes use of WideQ =>

**Comment by stefxx** [comment]
Any update already? Can't wait to test my new AC units 😉

**Comment by Michael1511** [comment]
What is the status of this? I am missing new devices as well. How can I try this new code?

**Comment by tinkerborg** [comment]
I've still been working on the new API, and made significant progress. Unfortunately, I don't have an update to report on my fork linked above. The new ThinQ architecture is different enough that I've spun up a new project [here](https://github.com/tinkerborg/thinq2-python) to support these devices. It's still rough around the edges, but the example script should get you through the oauth flow, list your devices, and listen for device events (currently dumped as raw mqtt events).

**Comment by stefxx** [comment]
Thanks, highly appreciated! Let's continue on the new project page!

**Comment by trarizakaria** [comment]
> @tinkerborg in case you continue working on this, I took your code and merged it into the original code (I gave up trying to maintain both in parallel). Feel free to continue on top of https://github.com/gladhorn/wideq/tree/api2_merged

this is the only repo that display my refrigator, waiting the possibility to monitore it. thank you guys for this work, sadly i don't know anything in coding. but i'm here to test.

thank you again and good luck with api v2
